ALTER TABLE devices ALTER COLUMN encryption_status TYPE VARCHAR(50);
ALTER TABLE devices ALTER COLUMN imaging_status TYPE VARCHAR(50);
ALTER TABLE devices ALTER COLUMN custody_status TYPE VARCHAR(50);
ALTER TABLE devices ALTER COLUMN category TYPE VARCHAR(50);
ALTER TABLE devices ALTER COLUMN evidence_type TYPE VARCHAR(100);
ALTER TABLE devices ALTER COLUMN retention_policy TYPE VARCHAR(50);
