"""Update CaseStatus enum values

Revision ID: e3df44719336
Revises: 36ecaa0a9428
Create Date: 2025-10-28 00:21:59.505287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3df44719336'
down_revision: Union[str, Sequence[str], None] = '36ecaa0a9428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    op.execute("CREATE TYPE devicetype AS ENUM ('MOBILE_PHONE', 'COMPUTER', 'LAPTOP', 'TABLET', 'HARD_DRIVE', 'USB_DRIVE', 'SD_CARD', 'SIM_CARD', 'ROUTER', 'OTHER')")
    op.execute("CREATE TYPE imagingstatus AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'VERIFIED')")
    
    op.add_column('devices', sa.Column('device_type', sa.Enum('MOBILE_PHONE', 'COMPUTER', 'LAPTOP', 'TABLET', 'HARD_DRIVE', 'USB_DRIVE', 'SD_CARD', 'SIM_CARD', 'ROUTER', 'OTHER', name='devicetype'), nullable=True))
    op.add_column('devices', sa.Column('imaging_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'VERIFIED', name='imagingstatus'), nullable=True))
    op.add_column('devices', sa.Column('imaging_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('imaging_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('imaging_tool', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('image_file_path', sa.String(length=500), nullable=True))
    op.add_column('devices', sa.Column('image_size_bytes', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('imaging_technician_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('current_location', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('analysis_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'devices', 'users', ['imaging_technician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'analysis_notes')
    op.drop_column('devices', 'current_location')
    op.drop_column('devices', 'imaging_technician_id')
    op.drop_column('devices', 'image_size_bytes')
    op.drop_column('devices', 'image_file_path')
    op.drop_column('devices', 'imaging_tool')
    op.drop_column('devices', 'imaging_completed_at')
    op.drop_column('devices', 'imaging_started_at')
    op.drop_column('devices', 'imaging_status')
    op.drop_column('devices', 'device_type')
    
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS devicetype')
    op.execute('DROP TYPE IF EXISTS imagingstatus')
    # ### end Alembic commands ###
