"""Add intelligence module tables

Revision ID: 0ddf58db62b3
Revises: cd90b8808fb0
Create Date: 2025-12-16 17:28:29.020574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ddf58db62b3'
down_revision: Union[str, Sequence[str], None] = 'cd90b8808fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_records',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('HUMINT', 'SIGINT', 'OSINT', 'CYBINT', 'FININT', 'OTHER', name='intelcategory'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='intelpriority'), nullable=False),
    sa.Column('status', sa.Enum('RAW', 'EVALUATED', 'CONFIRMED', 'ACTIONABLE', 'ARCHIVED', name='intelstatus'), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_records_title'), 'intelligence_records', ['title'], unique=False)
    op.create_table('intelligence_attachments',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['intelligence_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_case_links',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['intelligence_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_tags',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['intelligence_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_tags_tag'), 'intelligence_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_tags_tag'), table_name='intelligence_tags')
    op.drop_table('intelligence_tags')
    op.drop_table('intelligence_case_links')
    op.drop_table('intelligence_attachments')
    op.drop_index(op.f('ix_intelligence_records_title'), table_name='intelligence_records')
    op.drop_table('intelligence_records')
    # ### end Alembic commands ###
