"""Add work_activity enum to users and create team_activities table

Revision ID: 8f76903dba93
Revises: 13548486c725
Create Date: 2025-11-26 04:20:32.454653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f76903dba93'
down_revision: Union[str, Sequence[str], None] = '13548486c725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_activities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('MEETING', 'TRAVEL', 'TRAINING', 'LEAVE', name='workactivity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_activities_user_id'), 'team_activities', ['user_id'], unique=False)
    op.create_table('audit_archives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archive_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('entity_types', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('compressed_size', sa.Integer(), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_name')
    )
    op.create_index('ix_audit_archives_date_range', 'audit_archives', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_audit_archives_end_date'), 'audit_archives', ['end_date'], unique=False)
    op.create_index(op.f('ix_audit_archives_start_date'), 'audit_archives', ['start_date'], unique=False)
    op.create_index(op.f('ix_audit_archives_status'), 'audit_archives', ['status'], unique=False)
    op.create_table('audit_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('actions_to_audit', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('include_details', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('alert_on_failure', sa.Boolean(), nullable=False),
    sa.Column('minimum_severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_configurations_entity_type'), 'audit_configurations', ['entity_type'], unique=True)
    op.create_index(op.f('ix_audit_configurations_is_active'), 'audit_configurations', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('previous_checksum', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_timestamp', 'audit_logs', ['entity_type', 'entity_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_archived'), 'audit_logs', ['is_archived'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index('ix_audit_logs_session_timestamp', 'audit_logs', ['session_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_timestamp_desc', 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_timestamp', 'audit_logs', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_reports_created_by', 'compliance_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_compliance_reports_end_date'), 'compliance_reports', ['end_date'], unique=False)
    op.create_index(op.f('ix_compliance_reports_report_type'), 'compliance_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_compliance_reports_start_date'), 'compliance_reports', ['start_date'], unique=False)
    op.create_index(op.f('ix_compliance_reports_status'), 'compliance_reports', ['status'], unique=False)
    op.create_index('ix_compliance_reports_type_date', 'compliance_reports', ['report_type', 'start_date', 'end_date'], unique=False)
    op.create_table('compliance_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('compliance_rule', sa.String(length=200), nullable=True),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('related_audit_logs', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_violations_detected_at'), 'compliance_violations', ['detected_at'], unique=False)
    op.create_index(op.f('ix_compliance_violations_entity_id'), 'compliance_violations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_violations_entity_type'), 'compliance_violations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_compliance_violations_severity'), 'compliance_violations', ['severity'], unique=False)
    op.create_index('ix_compliance_violations_severity_detected', 'compliance_violations', ['severity', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index(op.f('ix_compliance_violations_status'), 'compliance_violations', ['status'], unique=False)
    op.create_index('ix_compliance_violations_type_status', 'compliance_violations', ['violation_type', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_violations_violation_type'), 'compliance_violations', ['violation_type'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('retention_period', sa.String(length=50), nullable=False),
    sa.Column('auto_archive', sa.Boolean(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_retention_policy_entity_name'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_retention_policies_entity_active', 'retention_policies', ['entity_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_retention_policies_entity_type'), 'retention_policies', ['entity_type'], unique=False)
    op.create_index(op.f('ix_retention_policies_is_active'), 'retention_policies', ['is_active'], unique=False)
    op.create_table('data_retention_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_succeeded', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['retention_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_jobs_entity_type'), 'data_retention_jobs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_retention_jobs_job_type'), 'data_retention_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_data_retention_jobs_scheduled_at'), 'data_retention_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_data_retention_jobs_status'), 'data_retention_jobs', ['status'], unique=False)
    op.create_index('ix_retention_jobs_scheduled', 'data_retention_jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_retention_jobs_type_status', 'data_retention_jobs', ['job_type', 'status'], unique=False)
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_collaborations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_collaborations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('work_activity', sa.Enum('MEETING', 'TRAVEL', 'TRAINING', 'LEAVE', name='workactivity'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_activity')
    op.alter_column('case_collaborations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_collaborations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_retention_jobs_type_status', table_name='data_retention_jobs')
    op.drop_index('ix_retention_jobs_scheduled', table_name='data_retention_jobs')
    op.drop_index(op.f('ix_data_retention_jobs_status'), table_name='data_retention_jobs')
    op.drop_index(op.f('ix_data_retention_jobs_scheduled_at'), table_name='data_retention_jobs')
    op.drop_index(op.f('ix_data_retention_jobs_job_type'), table_name='data_retention_jobs')
    op.drop_index(op.f('ix_data_retention_jobs_entity_type'), table_name='data_retention_jobs')
    op.drop_table('data_retention_jobs')
    op.drop_index(op.f('ix_retention_policies_is_active'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_entity_type'), table_name='retention_policies')
    op.drop_index('ix_retention_policies_entity_active', table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_compliance_violations_violation_type'), table_name='compliance_violations')
    op.drop_index('ix_compliance_violations_type_status', table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_status'), table_name='compliance_violations')
    op.drop_index('ix_compliance_violations_severity_detected', table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_severity'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_entity_type'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_entity_id'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_detected_at'), table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index('ix_compliance_reports_type_date', table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_status'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_start_date'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_report_type'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_end_date'), table_name='compliance_reports')
    op.drop_index('ix_compliance_reports_created_by', table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index('ix_audit_logs_user_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_archived'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_correlation_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_audit_configurations_is_active'), table_name='audit_configurations')
    op.drop_index(op.f('ix_audit_configurations_entity_type'), table_name='audit_configurations')
    op.drop_table('audit_configurations')
    op.drop_index(op.f('ix_audit_archives_status'), table_name='audit_archives')
    op.drop_index(op.f('ix_audit_archives_start_date'), table_name='audit_archives')
    op.drop_index(op.f('ix_audit_archives_end_date'), table_name='audit_archives')
    op.drop_index('ix_audit_archives_date_range', table_name='audit_archives')
    op.drop_table('audit_archives')
    op.drop_index(op.f('ix_team_activities_user_id'), table_name='team_activities')
    op.drop_table('team_activities')
    # ### end Alembic commands ###
