"""add_missing_fields_to_charges

Revision ID: 946de172f034
Revises: hi0123456789
Create Date: 2025-12-11 19:00:09.390327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '946de172f034'
down_revision: Union[str, Sequence[str], None] = 'hi0123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_items')
    op.alter_column('artefacts', 'evidence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_archives', 'entity_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=app.models.types.StringArray(),
               existing_nullable=False)
    op.alter_column('audit_configurations', 'actions_to_audit',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=app.models.types.StringArray(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cases_risk_flags'), table_name='cases', postgresql_using='gin')
    op.drop_constraint(op.f('chain_of_custody_evidence_id_fkey'), 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key(None, 'chain_of_custody', 'devices', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chain_of_custody_entries_evidence_id'), table_name='chain_of_custody_entries')
    op.drop_index(op.f('ix_chain_of_custody_entries_timestamp'), table_name='chain_of_custody_entries')
    op.add_column('charges', sa.Column('statute_section', sa.String(length=100), nullable=True))
    op.add_column('charges', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('charges', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'charges', 'users', ['created_by'], ['id'])
    op.alter_column('compliance_violations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('COMPLIANT', 'WARNING', 'VIOLATION', 'CRITICAL', name='compliancestatus'),
               existing_nullable=False)
    op.alter_column('compliance_violations', 'related_audit_logs',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=app.models.types.UUIDArray(),
               existing_nullable=True)
    op.drop_column('devices', 'device_type')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'analysis_notes')
    op.drop_column('devices', 'current_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('current_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('analysis_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'ANALYZED', 'BLOCKED', name='analysisstatus'), server_default=sa.text("'PENDING'::analysisstatus"), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_type', postgresql.ENUM('MOBILE_PHONE', 'COMPUTER', 'LAPTOP', 'TABLET', 'HARD_DRIVE', 'USB_DRIVE', 'SD_CARD', 'SIM_CARD', 'ROUTER', 'OTHER', 'DESKTOP', 'EXTERNAL_STORAGE', 'MEMORY_CARD', 'SERVER', 'NETWORK_DEVICE', name='devicetype'), autoincrement=False, nullable=True))
    op.alter_column('compliance_violations', 'related_audit_logs',
               existing_type=app.models.types.UUIDArray(),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.alter_column('compliance_violations', 'status',
               existing_type=sa.Enum('COMPLIANT', 'WARNING', 'VIOLATION', 'CRITICAL', name='compliancestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_column('charges', 'created_by')
    op.drop_column('charges', 'notes')
    op.drop_column('charges', 'statute_section')
    op.create_index(op.f('ix_chain_of_custody_entries_timestamp'), 'chain_of_custody_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chain_of_custody_entries_evidence_id'), 'chain_of_custody_entries', ['evidence_id'], unique=False)
    op.drop_constraint(None, 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key(op.f('chain_of_custody_evidence_id_fkey'), 'chain_of_custody', 'evidence_items', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_cases_risk_flags'), 'cases', ['risk_flags'], unique=False, postgresql_using='gin')
    op.alter_column('audit_configurations', 'actions_to_audit',
               existing_type=app.models.types.StringArray(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False)
    op.alter_column('audit_archives', 'entity_types',
               existing_type=app.models.types.StringArray(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False)
    op.alter_column('artefacts', 'evidence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('evidence_items',
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('DIGITAL', 'PHYSICAL', name='evidencecategory'), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_policy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('collected_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('evidence_items_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('evidence_items_collected_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_items_pkey'))
    )
    # ### end Alembic commands ###
