"""baseline_migration

Revision ID: be77e497018f
Revises: 
Create Date: 2025-12-16 02:10:41.364405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be77e497018f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False, comment='user_invite, password_reset, etc.'),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of allowed template variables'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('email_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='microsoft, gmail, zoho, smtp'),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False, comment='Encrypted SMTP password'),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('test_email', sa.String(length=255), nullable=True),
    sa.Column('last_test_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=50), nullable=True, comment='success, failed'),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forensic_reports',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_version', sa.String(length=100), nullable=True),
    sa.Column('tool_binary_hash', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_ndpa_dpia_high_risk', table_name='ndpa_impact_assessments')
    op.drop_index('ix_ndpa_dpia_review_dates', table_name='ndpa_impact_assessments')
    op.drop_index('ix_ndpa_dpia_status_date', table_name='ndpa_impact_assessments')
    op.drop_index('ix_ndpa_impact_assessments_approval_status', table_name='ndpa_impact_assessments')
    op.drop_index('ix_ndpa_impact_assessments_assessment_date', table_name='ndpa_impact_assessments')
    op.drop_index('ix_ndpa_impact_assessments_assessment_id', table_name='ndpa_impact_assessments')
    op.drop_table('ndpa_impact_assessments')
    op.drop_index('ix_ndpa_registration_compliance', table_name='ndpa_registration_records')
    op.drop_index('ix_ndpa_registration_records_registration_date', table_name='ndpa_registration_records')
    op.drop_index('ix_ndpa_registration_records_registration_status', table_name='ndpa_registration_records')
    op.drop_index('ix_ndpa_registration_records_renewal_due_date', table_name='ndpa_registration_records')
    op.drop_index('ix_ndpa_registration_renewal', table_name='ndpa_registration_records')
    op.drop_index('ix_ndpa_registration_status_date', table_name='ndpa_registration_records')
    op.drop_table('ndpa_registration_records')
    op.drop_index('ix_ndpa_processing_activities_processing_id', table_name='ndpa_processing_activities')
    op.drop_index('ix_ndpa_processing_activities_processing_purpose', table_name='ndpa_processing_activities')
    op.drop_index('ix_ndpa_processing_purpose_lawful', table_name='ndpa_processing_activities')
    op.drop_index('ix_ndpa_processing_registration', table_name='ndpa_processing_activities')
    op.drop_index('ix_ndpa_processing_risk_status', table_name='ndpa_processing_activities')
    op.drop_table('ndpa_processing_activities')
    op.drop_index('ix_ndpa_breach_nitda_notification', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_notifications_breach_discovered_at', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_notifications_breach_id', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_notifications_breach_occurred_at', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_notifications_breach_type', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_notifications_severity_level', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_severity_date', table_name='ndpa_breach_notifications')
    op.drop_index('ix_ndpa_breach_status', table_name='ndpa_breach_notifications')
    op.drop_table('ndpa_breach_notifications')
    op.drop_table('evidence_items')
    op.drop_index('ix_ndpa_data_subject_requests_data_subject_id', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_data_subject_requests_request_id', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_data_subject_requests_request_type', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_data_subject_requests_response_due_date', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_data_subject_requests_status', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_data_subject_requests_submitted_at', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_dsr_due_date', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_dsr_type_status', table_name='ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_dsr_verification', table_name='ndpa_data_subject_requests')
    op.drop_table('ndpa_data_subject_requests')
    op.drop_index('ix_ndpa_consent_cross_border', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_data_subject_purpose', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_records_consent_given_at', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_records_consent_type', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_records_data_subject_id', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_records_is_withdrawn', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_records_processing_purpose', table_name='ndpa_consent_records')
    op.drop_index('ix_ndpa_consent_status', table_name='ndpa_consent_records')
    op.drop_table('ndpa_consent_records')
    op.alter_column('artefacts', 'evidence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_archives', 'entity_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=app.models.types.StringArray(),
               existing_nullable=False)
    op.alter_column('audit_configurations', 'actions_to_audit',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=app.models.types.StringArray(),
               existing_nullable=False)
    op.drop_index('ix_cases_risk_flags', table_name='cases', postgresql_using='gin')
    op.drop_index('ix_cases_sensitivity_level', table_name='cases')
    op.drop_constraint('chain_of_custody_evidence_id_fkey', 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key(None, 'chain_of_custody', 'devices', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_chain_of_custody_entries_evidence_id', table_name='chain_of_custody_entries')
    op.drop_index('ix_chain_of_custody_entries_timestamp', table_name='chain_of_custody_entries')
    op.create_foreign_key(None, 'charges', 'users', ['created_by'], ['id'])
    op.alter_column('compliance_violations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('COMPLIANT', 'WARNING', 'VIOLATION', 'CRITICAL', name='compliancestatus'),
               existing_nullable=False)
    op.alter_column('compliance_violations', 'related_audit_logs',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=app.models.types.UUIDArray(),
               existing_nullable=True)
    op.drop_index('ix_compliance_violations_entity_type', table_name='compliance_violations')
    op.create_index('ix_compliance_violations_entity_type', 'compliance_violations', ['entity_type', 'entity_id'], unique=False)
    op.drop_column('devices', 'current_location')
    op.drop_column('devices', 'analysis_notes')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'device_type')
    op.alter_column('team_activity_attendees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_team_activity_attendees_activity_id', table_name='team_activity_attendees')
    op.drop_index('ix_team_activity_attendees_user_id', table_name='team_activity_attendees')
    op.drop_index('ix_user_sessions_expires', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_user_sessions_expires', 'user_sessions', ['expires_at', 'is_active'], unique=False)
    op.create_index('ix_team_activity_attendees_user_id', 'team_activity_attendees', ['user_id'], unique=False)
    op.create_index('ix_team_activity_attendees_activity_id', 'team_activity_attendees', ['activity_id'], unique=False)
    op.alter_column('team_activity_attendees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('devices', sa.Column('device_type', postgresql.ENUM('MOBILE_PHONE', 'COMPUTER', 'LAPTOP', 'TABLET', 'HARD_DRIVE', 'USB_DRIVE', 'SD_CARD', 'SIM_CARD', 'ROUTER', 'OTHER', 'DESKTOP', 'EXTERNAL_STORAGE', 'MEMORY_CARD', 'SERVER', 'NETWORK_DEVICE', name='devicetype'), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'ANALYZED', 'BLOCKED', name='analysisstatus'), server_default=sa.text("'PENDING'::analysisstatus"), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('analysis_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('current_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('ix_compliance_violations_entity_type', table_name='compliance_violations')
    op.create_index('ix_compliance_violations_entity_type', 'compliance_violations', ['entity_type'], unique=False)
    op.alter_column('compliance_violations', 'related_audit_logs',
               existing_type=app.models.types.UUIDArray(),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.alter_column('compliance_violations', 'status',
               existing_type=sa.Enum('COMPLIANT', 'WARNING', 'VIOLATION', 'CRITICAL', name='compliancestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.create_index('ix_chain_of_custody_entries_timestamp', 'chain_of_custody_entries', ['timestamp'], unique=False)
    op.create_index('ix_chain_of_custody_entries_evidence_id', 'chain_of_custody_entries', ['evidence_id'], unique=False)
    op.drop_constraint(None, 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key('chain_of_custody_evidence_id_fkey', 'chain_of_custody', 'evidence_items', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cases_sensitivity_level', 'cases', ['sensitivity_level'], unique=False)
    op.create_index('ix_cases_risk_flags', 'cases', ['risk_flags'], unique=False, postgresql_using='gin')
    op.alter_column('audit_configurations', 'actions_to_audit',
               existing_type=app.models.types.StringArray(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False)
    op.alter_column('audit_archives', 'entity_types',
               existing_type=app.models.types.StringArray(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False)
    op.alter_column('artefacts', 'evidence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('ndpa_consent_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_subject_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_subject_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_subject_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_subject_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('consent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('processing_purpose', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False),
    sa.Column('consent_given_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consent_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('consent_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('withdrawal_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_withdrawn', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('withdrawn_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('withdrawal_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retention_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('third_party_sharing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('third_parties', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('cross_border_transfer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('transfer_countries', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ndpa_consent_records_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_consent_records_pkey')
    )
    op.create_index('ix_ndpa_consent_status', 'ndpa_consent_records', ['is_withdrawn', 'consent_given_at'], unique=False)
    op.create_index('ix_ndpa_consent_records_processing_purpose', 'ndpa_consent_records', ['processing_purpose'], unique=False)
    op.create_index('ix_ndpa_consent_records_is_withdrawn', 'ndpa_consent_records', ['is_withdrawn'], unique=False)
    op.create_index('ix_ndpa_consent_records_data_subject_id', 'ndpa_consent_records', ['data_subject_id'], unique=False)
    op.create_index('ix_ndpa_consent_records_consent_type', 'ndpa_consent_records', ['consent_type'], unique=False)
    op.create_index('ix_ndpa_consent_records_consent_given_at', 'ndpa_consent_records', ['consent_given_at'], unique=False)
    op.create_index('ix_ndpa_consent_data_subject_purpose', 'ndpa_consent_records', ['data_subject_id', 'processing_purpose'], unique=False)
    op.create_index('ix_ndpa_consent_cross_border', 'ndpa_consent_records', ['cross_border_transfer', 'third_party_sharing'], unique=False)
    op.create_table('ndpa_data_subject_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_subject_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_subject_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_subject_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_subject_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('specific_data_requested', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('reason_for_request', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('submission_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('response_due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('response_provided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('verification_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_provided', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actions_taken', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('additional_info_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('additional_info_requested', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_info_provided', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fee_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('fee_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fee_currency', sa.VARCHAR(length=10), server_default=sa.text("'NGN'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fee_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='ndpa_data_subject_requests_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_data_subject_requests_pkey')
    )
    op.create_index('ix_ndpa_dsr_verification', 'ndpa_data_subject_requests', ['verification_completed', 'verification_date'], unique=False)
    op.create_index('ix_ndpa_dsr_type_status', 'ndpa_data_subject_requests', ['request_type', 'status'], unique=False)
    op.create_index('ix_ndpa_dsr_due_date', 'ndpa_data_subject_requests', ['response_due_date', 'status'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_submitted_at', 'ndpa_data_subject_requests', ['submitted_at'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_status', 'ndpa_data_subject_requests', ['status'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_response_due_date', 'ndpa_data_subject_requests', ['response_due_date'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_request_type', 'ndpa_data_subject_requests', ['request_type'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_request_id', 'ndpa_data_subject_requests', ['request_id'], unique=False)
    op.create_index('ix_ndpa_data_subject_requests_data_subject_id', 'ndpa_data_subject_requests', ['data_subject_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('DIGITAL', 'PHYSICAL', name='evidencecategory'), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_policy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('collected_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='evidence_items_case_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name='evidence_items_collected_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='evidence_items_pkey')
    )
    op.create_table('ndpa_breach_notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('breach_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('breach_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('breach_occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('breach_discovered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('breach_contained_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('breach_resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_categories_affected', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False),
    sa.Column('number_of_data_subjects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_subjects_notifiable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cause', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('likely_consequences', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('measures_taken', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preventive_measures', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notified_to_nitda', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('nitda_notification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nitda_notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nitda_reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nitda_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_subjects_notified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('notification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notification_delay_justification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remedial_actions', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.Column('remedial_actions_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('lessons_learned', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('breach_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('investigation_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('regulatory_action_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reported_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name='ndpa_breach_notifications_reported_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_breach_notifications_pkey')
    )
    op.create_index('ix_ndpa_breach_status', 'ndpa_breach_notifications', ['breach_resolved', 'investigation_completed'], unique=False)
    op.create_index('ix_ndpa_breach_severity_date', 'ndpa_breach_notifications', ['severity_level', sa.text('breach_occurred_at DESC')], unique=False)
    op.create_index('ix_ndpa_breach_notifications_severity_level', 'ndpa_breach_notifications', ['severity_level'], unique=False)
    op.create_index('ix_ndpa_breach_notifications_breach_type', 'ndpa_breach_notifications', ['breach_type'], unique=False)
    op.create_index('ix_ndpa_breach_notifications_breach_occurred_at', 'ndpa_breach_notifications', ['breach_occurred_at'], unique=False)
    op.create_index('ix_ndpa_breach_notifications_breach_id', 'ndpa_breach_notifications', ['breach_id'], unique=False)
    op.create_index('ix_ndpa_breach_notifications_breach_discovered_at', 'ndpa_breach_notifications', ['breach_discovered_at'], unique=False)
    op.create_index('ix_ndpa_breach_nitda_notification', 'ndpa_breach_notifications', ['notified_to_nitda', 'nitda_notification_date'], unique=False)
    op.create_table('ndpa_processing_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processing_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_controller', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('controller_contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('joint_controllers', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('processing_purpose', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lawful_basis', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lawful_basis_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False),
    sa.Column('sensitive_data_categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('data_subjects_categories', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('third_country_transfers', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('transfer_safeguards', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retention_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('retention_criteria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('security_measures', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.Column('is_high_risk', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('dpia_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('dpia_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('dpia_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('registered_with_nitda', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('nitda_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ndpa_processing_activities_created_by_fkey'),
    sa.ForeignKeyConstraint(['dpia_id'], ['ndpa_impact_assessments.id'], name='ndpa_processing_activities_dpia_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_processing_activities_pkey')
    )
    op.create_index('ix_ndpa_processing_risk_status', 'ndpa_processing_activities', ['is_high_risk', 'dpia_required'], unique=False)
    op.create_index('ix_ndpa_processing_registration', 'ndpa_processing_activities', ['registered_with_nitda', 'registration_date'], unique=False)
    op.create_index('ix_ndpa_processing_purpose_lawful', 'ndpa_processing_activities', ['processing_purpose', 'lawful_basis'], unique=False)
    op.create_index('ix_ndpa_processing_activities_processing_purpose', 'ndpa_processing_activities', ['processing_purpose'], unique=False)
    op.create_index('ix_ndpa_processing_activities_processing_id', 'ndpa_processing_activities', ['processing_id'], unique=False)
    op.create_table('ndpa_registration_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('business_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('physical_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dpo_appointed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('dpo_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dpo_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dpo_certification', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registration_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('renewal_due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('processing_activities_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('high_risk_processing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cross_border_transfers', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('third_country_list', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('compliance_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('last_assessment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_assessment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('violations_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('registration_fee_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('fee_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fee_currency', sa.VARCHAR(length=10), server_default=sa.text("'NGN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ndpa_registration_records_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_registration_records_pkey'),
    sa.UniqueConstraint('registration_number', name='ndpa_registration_records_registration_number_key')
    )
    op.create_index('ix_ndpa_registration_status_date', 'ndpa_registration_records', ['registration_status', 'registration_date'], unique=False)
    op.create_index('ix_ndpa_registration_renewal', 'ndpa_registration_records', ['renewal_due_date', 'registration_status'], unique=False)
    op.create_index('ix_ndpa_registration_records_renewal_due_date', 'ndpa_registration_records', ['renewal_due_date'], unique=False)
    op.create_index('ix_ndpa_registration_records_registration_status', 'ndpa_registration_records', ['registration_status'], unique=False)
    op.create_index('ix_ndpa_registration_records_registration_date', 'ndpa_registration_records', ['registration_date'], unique=False)
    op.create_index('ix_ndpa_registration_compliance', 'ndpa_registration_records', ['compliance_score', 'last_assessment_date'], unique=False)
    op.create_table('ndpa_impact_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('assessment_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('processing_activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('assessment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('assessor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('assessor_role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('high_risk_processing', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('systematic_monitoring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('large_scale_processing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sensitive_data_processing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('automated_decision_making', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('public_area_monitoring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('vulnerable_subjects', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('necessity_assessment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proportionality_assessment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_minimization_measures', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risks_identified', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.Column('risk_likelihood', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=False),
    sa.Column('risk_severity', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=False),
    sa.Column('risk_mitigation_measures', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.Column('residual_risks', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('residual_risk_acceptance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consultation_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('consultation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('consultation_outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nitda_guidance_received', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('approval_status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('review_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('next_review_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('monitoring_measures', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('monitoring_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('effectiveness_review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ndpa_impact_assessments_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndpa_impact_assessments_pkey')
    )
    op.create_index('ix_ndpa_impact_assessments_assessment_id', 'ndpa_impact_assessments', ['assessment_id'], unique=False)
    op.create_index('ix_ndpa_impact_assessments_assessment_date', 'ndpa_impact_assessments', ['assessment_date'], unique=False)
    op.create_index('ix_ndpa_impact_assessments_approval_status', 'ndpa_impact_assessments', ['approval_status'], unique=False)
    op.create_index('ix_ndpa_dpia_status_date', 'ndpa_impact_assessments', ['approval_status', sa.text('assessment_date DESC')], unique=False)
    op.create_index('ix_ndpa_dpia_review_dates', 'ndpa_impact_assessments', ['review_date', 'next_review_date'], unique=False)
    op.create_index('ix_ndpa_dpia_high_risk', 'ndpa_impact_assessments', ['high_risk_processing', 'consultation_required'], unique=False)
    op.drop_table('forensic_reports')
    op.drop_table('email_settings')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
